### ISSUE TITLE
add config.json or some things

### ISSUE THREAD

**Issue by rendiya** [openedoo/module_media#1]
for easiest to use add somthings file to configuration...
like config.py
```
{
   "static_file":"/some_folder",
   "max_file_size":"in mb";
}
```

**Comment by ghost** [comment]
thanks for your suggestion :heart: .

do you mean extending the `openedoo_project` config to create some kind of rule to validate the uploaded file?.


<hr>

*This comment is translated into Bahasa*

<hr>

Terima kasih atas sarannya :heart:. 


Apa Maksudnya meng-extend `openoo_project` config untuk membuat semacam aturan untuk memvalidasi file yang diunggah ?.

**Comment by ghost** [comment]
no further discussion? i will close this issue.
